### ISSUE TITLE
Range error in `fragmentation.rb`

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/embed-code#10]
An attempt to embed a Groovy code using this code:

```
<?embed-code file="examples/hello/build.gradle" start="*plugins*" end="}*"?>  
` ` `groovy
` ` `
```
resulted in this error:
```
jekyll 3.8.7 | Error:  float Inf out of range of integer
Traceback (most recent call last):
        40: from /Users/sanders/.rbenv/versions/2.7.1/bin/bundle:23:in `<main>'
        39: from /Users/sanders/.rbenv/versions/2.7.1/bin/bundle:23:in `load'
        38: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
        37: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
        36: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
        35: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/cli.rb:24:in `start'
        34: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
        33: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
        32: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
        31: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        30: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        29: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/cli.rb:476:in `exec'
        28: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
        27: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
        26: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
        25: from /Users/sanders/.rbenv/versions/2.7.1/bin/jekyll:23:in `<top (required)>'
        24: from /Users/sanders/.rbenv/versions/2.7.1/bin/jekyll:23:in `load'
        23: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/jekyll-3.8.7/exe/jekyll:15:in `<top (required)>'
        22: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        21: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        20: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        19: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        18: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        17: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/embed-code-5e919b38bb33/lib/commands/embed_command.rb:36:in `block (2 levels) in init_with_program'
        16: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/embed-code-5e919b38bb33/lib/commands/embed_command.rb:41:in `process'
        15: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/embed-code-5e919b38bb33/lib/commands/fragmentation.rb:64:in `write_fragment_files'
        14: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/embed-code-5e919b38bb33/lib/commands/fragmentation.rb:64:in `each'
        13: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/embed-code-5e919b38bb33/lib/commands/fragmentation.rb:66:in `block in write_fragment_files'
        12: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/embed-code-5e919b38bb33/lib/commands/fragmentation.rb:66:in `glob'
        11: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/embed-code-5e919b38bb33/lib/commands/fragmentation.rb:68:in `block (2 levels) in write_fragment_files'
        10: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/embed-code-5e919b38bb33/lib/commands/fragmentation.rb:83:in `write_fragments'
         9: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/embed-code-5e919b38bb33/lib/commands/fragmentation.rb:83:in `each'
         8: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/embed-code-5e919b38bb33/lib/commands/fragmentation.rb:85:in `block in write_fragments'
         7: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/embed-code-5e919b38bb33/lib/commands/fragmentation.rb:248:in `write_to'
         6: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/embed-code-5e919b38bb33/lib/commands/fragmentation.rb:334:in `write'
         5: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/embed-code-5e919b38bb33/lib/commands/fragmentation.rb:348:in `write_lines'
         4: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/embed-code-5e919b38bb33/lib/commands/fragmentation.rb:348:in `open'
         3: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/embed-code-5e919b38bb33/lib/commands/fragmentation.rb:350:in `block in write_lines'
         2: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/embed-code-5e919b38bb33/lib/commands/fragmentation.rb:350:in `each'
         1: from /Users/sanders/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/embed-code-5e919b38bb33/lib/commands/fragmentation.rb:351:in `block (2 levels) in write_lines'
/Users/sanders/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/embed-code-5e919b38bb33/lib/commands/fragmentation.rb:351:in `[]': float Inf out of range of integer (RangeError)
```

**Comment by alexander-yevsyukov** [comment]
What's more interesting is that even if I remove the embedding instruction, I still get the error.

**Comment by dmdashenkov** [comment]
The quick fix is to specify the `code_includes` param, e.g.:
```yaml
embed_code:
  code_root: ./_samples
  documentation_root: ./docs
  code_includes: ['**/*.java', '**/*.js', '**/*.gradle']
```

The actual fix is coming soon.
